### ISSUE TITLE
Set transparent terminal background in Ubuntu with dconf

### ISSUE THREAD

**Issue by dhermes** [dhermes/dotfiles#10]
From http://askubuntu.com/a/450159

> The terminal in Ubuntu 14.04 supports profiles. In order to get a transparent terminal follow these steps:
> 1. Open a terminal
> 2. Select _Profile preferences_ in the menu _Edit_
> 3. Select the _Background_ tab
> 4. Check the _Transparent background_ radio button
> 5. Adjust the _Shade background_ or _image background_ slider to your preference

**Comment by Amr116** [comment]
after upgradeing my ubuntu can not finde background tab ..!

**Comment by dhermes** [comment]
Sorry to hear that.
